import {useRef,useState} from "react"; import {UploadCloud,FileJson,X,Play} from "lucide-react"; import type {Dataset} from "../types/dns"; import {parseDnsJson} from "../parser/dnsParser";
export function Upload({datasets,onAdd,onAnalyze}:{datasets:Dataset[];onAdd:(d:Dataset[])=>void;onAnalyze:()=>void}){
 const ref=useRef<HTMLInputElement>(null),[drag,setDrag]=useState(false),[error,setError]=useState("");
 async function read(fs:FileList|File[]){setError("");const a:Dataset[]=[];for(const f of Array.from(fs)){if(!f.name.toLowerCase().endsWith(".json"))continue;try{a.push(parseDnsJson(await f.text(),f.name))}catch{setError(`Could not parse ${f.name}. Please select a valid DNS run JSON.`)}}if(a.length)onAdd([...datasets,...a])}
 return <div><div className="upload-hero"><div><span className="eyebrow">DATA IMPORT</span><h1>Turn DNS run JSONs into useful graphs.</h1><p>Upload one or many files. The analyzer extracts domains, resolvers, latency, response codes and run metadata directly in your browser.</p></div><div className="upload-icon"><UploadCloud size={34}/></div></div>
 <div className={`dropzone ${drag?"dragging":""}`} onDragOver={e=>{e.preventDefault();setDrag(true)}} onDragLeave={()=>setDrag(false)} onDrop={e=>{e.preventDefault();setDrag(false);void read(e.dataTransfer.files)}} onClick={()=>ref.current?.click()}><UploadCloud size={42}/><h2>Drop JSON files here</h2><p>or click to browse · multiple files supported</p><input ref={ref} type="file" accept=".json,application/json" multiple hidden onChange={e=>e.target.files&&void read(e.target.files)}/></div>
 {error&&<div className="error">{error}</div>}
 {datasets.length>0&&<section className="panel"><div className="panel-header"><div><h2>Uploaded datasets</h2><p>{datasets.length} file{datasets.length!==1?"s":""} ready for analysis</p></div><button className="primary-button" onClick={onAnalyze}><Play size={16}/> Analyze</button></div><div className="dataset-list">{datasets.map(d=><div className="dataset-row" key={d.id}><FileJson size={19}/><div className="dataset-name"><strong>{d.fileName}</strong><span>{d.interfaceName} · PID {d.runPid}</span></div><div className="dataset-meta">{d.queryCount} queries</div><button className="icon-button" onClick={()=>onAdd(datasets.filter(x=>x.id!==d.id))}><X size={16}/></button></div>)}</div></section>}
 {!datasets.length&&<div className="empty-note">Your JSON is processed locally in this browser session; no server is required.</div>}</div>
}